[package]
name = "pro-serde-versioned-derive"
version = "1.0.2"
edition = "2021"
description = "Macros for use with pro-serde-versioned"
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.15", features = ["extra-traits"] }
quote = "1.0.26"
proc-macro2 = "1.0.56"
