#  ┌───────────────────────────────────────────────────────────────────────────┐
#  │                                                                           │
#  │  ██████╗ ██████╗  ██████╗   Copyright (C) 2022, The Prospective Company   │
#  │  ██╔══██╗██╔══██╗██╔═══██╗                                                │
#  │  ██████╔╝██████╔╝██║   ██║  This file is part of the Procss library,      │
#  │  ██╔═══╝ ██╔══██╗██║   ██║  distributed under the terms of the            │
#  │  ██║     ██║  ██║╚██████╔╝  Apache License 2.0.  The full license can     │
#  │  ╚═╝     ╚═╝  ╚═╝ ╚═════╝   be found in the LICENSE file.                 │
#  │                                                                           │
#  └───────────────────────────────────────────────────────────────────────────┘

name: CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["*"]
    workflow_dispatch: {}

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-20.04]
                rust_toolchain: [nightly-2023-05-09]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: ${{ matrix.rust_toolchain }}
                  override: true

            - uses: Swatinem/rust-cache@v2
            #   with:
            # The cargo workspaces and target directory configuration.
            # These entries are separated by newlines and have the form
            # `$workspace -> $target`. The `$target` part is treated as a directory
            # relative to the `$workspace` and defaults to "target" if not explicitly given.
            # default: ". -> target"
            #   workspaces: ""
            - name: Build
              run: cargo build --verbose
            - name: Run tests
              run: |
                  cargo test --verbose

